/*
Copyright Â©Â 2023 Ishimaki Kazutoyo. All rights reserved.
This source code or any portion thereof must not beÂ  
reproduced or used in any manner whatsoever.
*/
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteAlways]
public class AspeckKeeper : MonoBehaviour
{
    [SerializeField]
    private Camera targetCamera; //ï¿½ÎÛ‚Æ‚ï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½

    [SerializeField]
    private Vector2 aspectVec; //ï¿½Ú“Iï¿½ğ‘œ“x
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        var screenAspect = Screen.width / (float)Screen.height; //ï¿½ï¿½Ê‚ÌƒAï¿½Xï¿½yï¿½Nï¿½gï¿½ï¿½
        var targetAspect = aspectVec.x / aspectVec.y; //ï¿½Ú“Iï¿½ÌƒAï¿½Xï¿½yï¿½Nï¿½gï¿½ï¿½

        var magRate = targetAspect / screenAspect; //ï¿½Ú“Iï¿½Aï¿½Xï¿½yï¿½Nï¿½gï¿½ï¿½É‚ï¿½ï¿½é‚½ï¿½ß‚Ì”{ï¿½ï¿½

        var viewportRect = new Rect(0, 0, 1, 1); //Viewportï¿½ï¿½ï¿½ï¿½ï¿½lï¿½ï¿½Rectï¿½ï¿½ï¿½ì¬

        if(magRate < 1)
        {
            viewportRect.width = magRate; //ï¿½gï¿½pï¿½ï¿½ï¿½é‰¡ï¿½ï¿½ï¿½ï¿½ÏX
            viewportRect.x = 0.5f - viewportRect.width * 0.5f; //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        }
        else
        {
            viewportRect.height = 1 / magRate; //ï¿½gï¿½pï¿½ï¿½ï¿½ï¿½cï¿½ï¿½ï¿½ï¿½ÏX
            viewportRect.y = 0.5f - viewportRect.height * 0.5f; //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        }

        targetCamera.rect = viewportRect; //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Viewportï¿½É“Kï¿½p
    }
}
